# Generated by Django 5.2.2 on 2025-06-10 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school_units_access',
            field=models.ManyToManyField(blank=True, help_text='School units this user has permissions to access data from.', related_name='users_with_access', to='core.schoolunit', verbose_name='school units access'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active_school_unit',
            field=models.ForeignKey(blank=True, help_text='The school unit this user is currently primarily associated with or operating within.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles_active_here', to='core.schoolunit', verbose_name='active school unit'),
        ),
    ]
