# Generated by Django 5.2.2 on 2025-06-06 14:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_student_rejection_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Ano letivo, ex: 2024.', unique=True, verbose_name='year')),
                ('start_date', models.DateField(help_text='Data de início do ano letivo.', verbose_name='start date')),
                ('end_date', models.DateField(help_text='Data de término do ano letivo.', verbose_name='end date')),
                ('is_active', models.BooleanField(default=False, help_text='Indica se este é o ano letivo corrente/ativo no sistema.', verbose_name='is active?')),
            ],
            options={
                'verbose_name': 'School Year',
                'verbose_name_plural': 'School Years',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da disciplina, ex: "Matemática".', max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Descrição ou ementa da disciplina.', null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome ou identificador da turma, ex: "Turma A", "101", "Manhã".', max_length=100, verbose_name='name')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='students.gradelevel', verbose_name='grade level')),
                ('main_teacher', models.ForeignKey(blank=True, help_text='Professor principal ou regente da turma, se aplicável.', limit_choices_to={'user_type': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_taught_classes', to=settings.AUTH_USER_MODEL, verbose_name='main teacher')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='academics.schoolyear', verbose_name='school year')),
            ],
            options={
                'verbose_name': 'School Class',
                'verbose_name_plural': 'School Classes',
                'ordering': ['school_year', 'grade_level', 'name'],
                'unique_together': {('name', 'school_year', 'grade_level')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True, help_text='Data em que a matrícula foi efetivada nesta turma.', verbose_name='enrollment date')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('COMPLETED', 'Concluída'), ('TRANSFERRED_OUT', 'Transferido (Saída)'), ('DROPPED_OUT', 'Abandono/Evasão')], default='ACTIVE', help_text='Status atual da matrícula do aluno na turma.', max_length=20, verbose_name='status')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student', verbose_name='student')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='academics.schoolclass', verbose_name='school class')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['school_class', 'student__user__first_name', 'student__user__last_name'],
                'unique_together': {('student', 'school_class')},
            },
        ),
        migrations.CreateModel(
            name='SchoolEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título do evento.', max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada do evento.', null=True, verbose_name='description')),
                ('start_time', models.DateTimeField(help_text='Data e hora de início do evento.', verbose_name='start time')),
                ('end_time', models.DateTimeField(help_text='Data e hora de término do evento.', verbose_name='end time')),
                ('event_type', models.CharField(choices=[('EXAM', 'Prova/Avaliação'), ('MEETING', 'Reunião'), ('HOLIDAY', 'Feriado/Recesso'), ('SCHOOL_ACTIVITY', 'Atividade Escolar'), ('OTHER', 'Outro Evento')], help_text='Tipo do evento.', max_length=30, verbose_name='event type')),
                ('is_school_wide', models.BooleanField(default=False, help_text='Marque se o evento é para toda a escola (ignora turmas/séries específicas).', verbose_name='is school-wide?')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o evento (Professor, Secretaria, Admin).', limit_choices_to={'user_type__in': ['TEACHER', 'STAFF', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('target_grade_levels', models.ManyToManyField(blank=True, help_text='Selecione as séries específicas. Usado se não for para turmas específicas ou toda a escola.', related_name='events', to='students.gradelevel', verbose_name='target grade levels')),
                ('target_school_classes', models.ManyToManyField(blank=True, help_text='Selecione as turmas específicas para este evento. Deixe em branco se for para uma série ou para toda a escola.', related_name='events', to='academics.schoolclass', verbose_name='target school classes')),
            ],
            options={
                'verbose_name': 'School Event',
                'verbose_name_plural': 'School Events',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='GradingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do período, ex: "1º Bimestre", "Trimestre Final".', max_length=100, verbose_name='name')),
                ('start_date', models.DateField(help_text='Data de início do período de avaliação.', verbose_name='start date')),
                ('end_date', models.DateField(help_text='Data de término do período de avaliação.', verbose_name='end date')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_periods', to='academics.schoolyear', verbose_name='school year')),
            ],
            options={
                'verbose_name': 'Grading Period',
                'verbose_name_plural': 'Grading Periods',
                'ordering': ['school_year', 'start_date'],
                'unique_together': {('name', 'school_year')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_name', models.CharField(help_text='Nome ou descrição da avaliação, ex: "Prova Bimestral 1", "Trabalho em Grupo - Revolução Francesa", "Participação em Aula".', max_length=100, verbose_name='assessment name')),
                ('grade_value', models.DecimalField(decimal_places=2, help_text='Valor da nota obtida pelo aluno.', max_digits=5, verbose_name='grade value')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Peso desta nota para cálculo de média ponderada (ex: 0.4 para 40%). Deixar em branco se não aplicável ou se a média for simples.', max_digits=3, null=True, verbose_name='weight')),
                ('grading_date', models.DateField(default=django.utils.timezone.now, help_text='Data de lançamento ou da realização da avaliação.', verbose_name='grading date')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.enrollment', verbose_name='enrollment')),
                ('grading_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.gradingperiod', verbose_name='grading period')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.subject', verbose_name='subject')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['enrollment', 'subject', 'grading_period', 'grading_date'],
            },
        ),
        migrations.CreateModel(
            name='DidacticMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título do material didático.', max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Breve descrição do material.', null=True, verbose_name='description')),
                ('file', models.FileField(help_text='Arquivo do material didático (PDF, DOCX, PPTX, etc.).', upload_to='didactic_materials/%Y/%m/', verbose_name='file')),
                ('upload_date', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o material foi enviado.', verbose_name='upload date')),
                ('uploader', models.ForeignKey(help_text='Usuário que fez o upload do material (Professor, Secretaria, Admin).', limit_choices_to={'user_type__in': ['TEACHER', 'STAFF', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL, verbose_name='uploader')),
                ('school_class', models.ForeignKey(blank=True, help_text='Associe a uma turma específica, ou deixe em branco se for geral para a disciplina/série.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='didactic_materials', to='academics.schoolclass', verbose_name='school class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='didactic_materials', to='academics.subject', verbose_name='subject')),
            ],
            options={
                'verbose_name': 'Didactic Material',
                'verbose_name_plural': 'Didactic Materials',
                'ordering': ['subject', '-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Data da aula para a qual a frequência está sendo registrada.', verbose_name='date')),
                ('status', models.CharField(choices=[('PRESENT', 'Presente'), ('ABSENT', 'Ausente'), ('JUSTIFIED_ABSENCE', 'Ausência Justificada')], help_text='Status de presença do aluno na aula.', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, help_text='Observações, como a justificativa para uma ausência.', null=True, verbose_name='notes')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academics.enrollment', verbose_name='enrollment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academics.subject', verbose_name='subject')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', 'enrollment', 'subject'],
                'unique_together': {('enrollment', 'subject', 'date')},
            },
        ),
    ]
