# Generated by Django 5.2.2 on 2025-06-06 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.schoolclass', verbose_name='school class')),
                ('school_year', models.ForeignKey(help_text='Ano letivo para o qual esta atribuição é válida.', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.schoolyear', verbose_name='school year')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.subject', verbose_name='subject')),
                ('teacher', models.ForeignKey(help_text='Professor atribuído.', limit_choices_to={'user_type': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'Teacher Assignment',
                'verbose_name_plural': 'Teacher Assignments',
                'ordering': ['school_year', 'school_class__grade_level__order_in_sequence', 'school_class__name', 'subject__name'],
                'unique_together': {('teacher', 'school_class', 'subject', 'school_year')},
            },
        ),
    ]
