# Generated by Django 5.2.2 on 2025-06-06 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_teacherassignment'),
        ('students', '0002_student_rejection_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='publication date')),
                ('target_user_types', models.JSONField(blank=True, help_text="Lista de tipos de usuários que devem ver este comunicado, ex: ['STUDENT', 'PARENT']. Deixe em branco para todos os tipos aplicáveis por outras regras de direcionamento.", null=True, verbose_name='target user types')),
                ('is_school_wide', models.BooleanField(default=False, help_text='Marque se o comunicado é para toda a escola (ignora outros direcionamentos específicos se marcado).', verbose_name='is school-wide?')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Data após a qual o comunicado não será mais exibido proeminentemente.', null=True, verbose_name='expiry date')),
                ('author', models.ForeignKey(limit_choices_to={'user_type__in': ['STAFF', 'ADMIN', 'TEACHER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_announcements', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('target_grade_levels', models.ManyToManyField(blank=True, help_text='Selecione as séries específicas para este comunicado. Vazio significa todas as séries aplicáveis por outras regras.', related_name='announcements', to='students.gradelevel', verbose_name='target grade levels')),
                ('target_school_classes', models.ManyToManyField(blank=True, help_text='Selecione as turmas específicas. Vazio significa todas as turmas aplicáveis por outras regras.', related_name='announcements', to='academics.schoolclass', verbose_name='target school classes')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-publication_date'],
            },
        ),
    ]
