# Generated by Django 5.2.2 on 2025-06-06 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da série/nível escolar, ex: "1º Ano Ensino Fundamental".', max_length=100, unique=True, verbose_name='name')),
                ('order_in_sequence', models.PositiveSmallIntegerField(help_text='Ordem em que a série aparece na progressão escolar, ex: 1 para a primeira série, 2 para a segunda, etc.', unique=True, verbose_name='order in sequence')),
            ],
            options={
                'verbose_name': 'Grade Level',
                'verbose_name_plural': 'Grade Levels',
                'ordering': ['order_in_sequence'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user account')),
                ('enrollment_date', models.DateField(blank=True, help_text='Data em que a matrícula do aluno foi efetivada.', null=True, verbose_name='enrollment date')),
                ('registration_status', models.CharField(choices=[('PRE_REGISTERED', 'Pré-Cadastrado'), ('PENDING_VALIDATION', 'Pendente de Validação'), ('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo'), ('TRANSFERRED', 'Transferido'), ('GRADUATED', 'Graduado')], default='PRE_REGISTERED', help_text='Status atual do cadastro/matrícula do aluno.', max_length=20, verbose_name='registration status')),
                ('school_entry_date', models.DateField(blank=True, help_text='Data de ingresso do aluno na instituição (pode ser diferente da data de matrícula no ano letivo atual).', null=True, verbose_name='school entry date')),
                ('allergies', models.TextField(blank=True, help_text='Informações sobre alergias do aluno.', null=True, verbose_name='allergies')),
                ('observations', models.TextField(blank=True, help_text='Outras observações relevantes sobre o aluno.', null=True, verbose_name='observations')),
                ('grade_level_pretended', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aspiring_students', to='students.gradelevel', verbose_name='grade level pretended')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('RG_ALUNO', 'RG do Aluno'), ('CPF_ALUNO', 'CPF do Aluno'), ('COMP_RESIDENCIA_RESP', 'Comprovante de Residência do Responsável'), ('CARTEIRA_VACINACAO', 'Carteira de Vacinação'), ('HIST_ESCOLAR', 'Histórico Escolar da Escola Anterior'), ('LAUDO_MEDICO', 'Laudo Médico (para necessidades especiais)'), ('FOTO_3X4', 'Foto 3x4 Recente'), ('RG_RESPONSAVEL', 'RG do Responsável'), ('CPF_RESPONSAVEL', 'CPF do Responsável'), ('DECLARACAO_QUITACAO_ESCOLA_ANT', 'Declaração de Quitação da Escola Anterior'), ('OUTRO', 'Outro Documento')], help_text='Tipo do documento.', max_length=50, verbose_name='document type')),
                ('document_name', models.CharField(blank=True, help_text='Nome descritivo do documento, ex: RG Frente, Comprovante Março/2024. Preenchido se "Outro Documento" ou para especificar.', max_length=255, verbose_name='document name')),
                ('file', models.FileField(help_text='Arquivo do documento.', upload_to='student_documents/%Y/%m/%d/', verbose_name='file')),
                ('upload_date', models.DateField(auto_now_add=True, help_text='Data em que o arquivo foi enviado.', verbose_name='upload date')),
                ('validation_status', models.CharField(choices=[('PENDING', 'Pendente de Validação'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], default='PENDING', help_text='Status da validação do documento pela secretaria.', max_length=10, verbose_name='validation status')),
                ('is_optional', models.BooleanField(default=False, help_text='Marque se este tipo de documento é opcional para a matrícula.', verbose_name='is optional?')),
                ('notes', models.TextField(blank=True, help_text='Observações da secretaria sobre o documento (ex: motivo da rejeição).', null=True, verbose_name='notes')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'Student Document',
                'verbose_name_plural': 'Student Documents',
                'ordering': ['student', '-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentParentAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('FATHER', 'Pai'), ('MOTHER', 'Mãe'), ('LEGAL_GUARDIAN', 'Responsável Legal'), ('FINANCIAL_GUARDIAN', 'Responsável Financeiro'), ('OTHER', 'Outro')], help_text='Tipo de relação entre o responsável e o aluno.', max_length=30, verbose_name='relationship type')),
                ('parent_user', models.ForeignKey(help_text='Usuário do tipo "Pai/Responsável".', limit_choices_to={'user_type': 'PARENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='child_associations', to=settings.AUTH_USER_MODEL, verbose_name='parent/guardian user')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_associations', to='students.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'Student-Parent Association',
                'verbose_name_plural': 'Student-Parent Associations',
                'ordering': ['student', 'parent_user'],
                'unique_together': {('student', 'parent_user', 'relationship_type')},
            },
        ),
    ]
