# Generated by Django 5.2.2 on 2025-06-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Motivo pelo qual a matrícula ou pré-cadastro foi rejeitado.', null=True, verbose_name='rejection reason'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_status',
            field=models.CharField(choices=[('PRE_REGISTERED', 'Pré-Cadastrado'), ('PENDING_VALIDATION', 'Pendente de Validação'), ('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo'), ('TRANSFERRED', 'Transferido'), ('GRADUATED', 'Graduado'), ('REJECTED', 'Rejeitado')], default='PRE_REGISTERED', help_text='Status atual do cadastro/matrícula do aluno.', max_length=20, verbose_name='registration status'),
        ),
    ]
