# Generated by Django 5.2.2 on 2025-06-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='school name')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, help_text='Is this school unit currently active?', verbose_name='is active')),
            ],
            options={
                'verbose_name': 'School Unit',
                'verbose_name_plural': 'School Units',
                'ordering': ['name'],
            },
        ),
    ]
