# Generated by Django 5.2.2 on 2025-06-06 15:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_teacherassignment'),
        ('students', '0002_student_rejection_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Descrição da taxa (ex: Mensalidade Março/2024, Taxa de Material Didático).', max_length=255, verbose_name='description')),
                ('due_date', models.DateField(help_text='Data de vencimento.', verbose_name='due date')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valor original da taxa.', max_digits=10, verbose_name='amount')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('OVERDUE', 'Vencido'), ('CANCELED', 'Cancelado'), ('PARTIALLY_PAID', 'Parcialmente Pago')], default='PENDING', help_text='Status atual da taxa.', max_length=20, verbose_name='status')),
                ('payment_gateway_id', models.CharField(blank=True, help_text='ID externo do boleto/cobrança no gateway de pagamento.', max_length=255, null=True, verbose_name='payment gateway ID')),
                ('barcode', models.CharField(blank=True, help_text='Código de barras do boleto, se aplicável.', max_length=255, null=True, verbose_name='barcode')),
                ('notes', models.TextField(blank=True, help_text='Observações internas sobre a taxa (ex: negociações, isenções parciais).', null=True, verbose_name='notes')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor do desconto aplicado.', max_digits=10, verbose_name='discount amount')),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor da multa por atraso.', max_digits=10, verbose_name='penalty amount')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Valor efetivamente pago.', max_digits=10, null=True, verbose_name='amount paid')),
                ('payment_date', models.DateField(blank=True, help_text='Data em que o pagamento foi efetuado/confirmado.', null=True, verbose_name='payment date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('school_year', models.ForeignKey(help_text='Ano letivo da taxa.', on_delete=django.db.models.deletion.PROTECT, related_name='fees', to='academics.schoolyear', verbose_name='school year')),
                ('student', models.ForeignKey(help_text='Aluno ao qual esta taxa se refere.', on_delete=django.db.models.deletion.PROTECT, related_name='fees', to='students.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'Fee',
                'verbose_name_plural': 'Fees',
                'ordering': ['due_date', 'student'],
            },
        ),
        migrations.CreateModel(
            name='FeeEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('field_changed', models.CharField(default='amount', help_text='Campo que foi alterado (ex: amount, due_date, status).', max_length=50, verbose_name='field changed')),
                ('previous_value', models.CharField(help_text='Valor anterior do campo.', max_length=255, verbose_name='previous value')),
                ('new_value', models.CharField(help_text='Novo valor do campo.', max_length=255, verbose_name='new value')),
                ('reason', models.TextField(help_text='Motivo da alteração manual.', verbose_name='reason')),
                ('edited_by', models.ForeignKey(blank=True, help_text='Usuário (staff) que realizou a alteração.', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_edits', to=settings.AUTH_USER_MODEL, verbose_name='edited by')),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='financials.fee', verbose_name='fee')),
            ],
            options={
                'verbose_name': 'Fee Edit Log',
                'verbose_name_plural': 'Fee Edit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, help_text='Data em que o pagamento foi efetuado/registrado.', verbose_name='payment date')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Valor efetivamente pago nesta transação.', max_digits=10, verbose_name='amount paid')),
                ('payment_method', models.CharField(choices=[('BOLETO', 'Boleto Bancário'), ('CREDIT_CARD', 'Cartão de Crédito'), ('PIX', 'PIX'), ('CASH', 'Dinheiro'), ('BANK_TRANSFER', 'Transferência Bancária'), ('OTHER', 'Outro')], help_text='Método utilizado para o pagamento.', max_length=20, verbose_name='payment method')),
                ('transaction_id', models.CharField(blank=True, help_text='ID da transação no gateway de pagamento ou referência interna/documento.', max_length=255, null=True, verbose_name='transaction ID')),
                ('notes', models.TextField(blank=True, help_text='Observações sobre o pagamento (ex: pago na secretaria, referente a acordo).', null=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('confirmed_by', models.ForeignKey(blank=True, help_text='Usuário (staff) que confirmou o recebimento do pagamento (se aplicável).', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL, verbose_name='confirmed by')),
                ('fee', models.ForeignKey(help_text='Taxa à qual este pagamento se refere.', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='financials.fee', verbose_name='fee')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
