# Generated by Django 5.2.2 on 2025-06-10 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Successful'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('CREATED', 'Object Created'), ('UPDATED', 'Object Updated'), ('DELETED', 'Object Deleted'), ('VIEWED', 'Object/View Accessed'), ('EXPORTED', 'Data Exported')], db_index=True, max_length=50, verbose_name='action type')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='timestamp')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('target_object_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='target object ID')),
                ('target_object_repr', models.CharField(blank=True, help_text='String representation of the target object at the time of logging.', max_length=255, null=True, verbose_name='target object representation')),
                ('details', models.JSONField(blank=True, help_text='Additional details about the action, e.g., changed fields, parameters.', null=True, verbose_name='details')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='target content type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['target_content_type', 'target_object_id'], name='auditing_au_target__e74d65_idx'), models.Index(fields=['action_type', 'timestamp'], name='auditing_au_action__c0000a_idx')],
            },
        ),
    ]
